# -*- coding: utf-8 -*-
"""SMF_assignment1_Question3ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KhEbN3npq9bzsogLvX1XOtQ-mGnQpRnb

# Question 3 Simulation part
"""

import numpy as np

def returns_to_origin(d, n_steps):

    pos = np.zeros(d, dtype=int)

    for _ in range(n_steps):

        coord = np.random.randint(d)
        direction = np.random.choice([-1, 1])

        pos[coord] += direction

        if np.all(pos == 0):
            return True

    return False


def estimate_return_probability(d,
                                n_steps=1000,
                                n_paths=1000):

    count = 0

    for _ in range(n_paths):

        if returns_to_origin(d, n_steps):
            count += 1

    return count / n_paths


for d in [1,2,3]:

    p = estimate_return_probability(
        d,
        n_steps=1000,
        n_paths=1000
    )

    print(f"d={d}: {p:.4f}")

"""# Interpretation

## 1. d = 1

* Almost every path returns.

* This agrees with recurrence.

## 2. d = 2

* Most paths return.

* Again consistent with recurrence.

## 3. d = 3
* Many paths never return.

* Suggests transience.
"""

for n in [100,1000,10000]:

    print(f"\nPath length = {n}")

    for d in [1,2,3]:

        p = estimate_return_probability(
            d,
            n_steps=n,
            n_paths=1000
        )

        print(f"d={d}: {p:.4f}")

"""1. For d=1 as path length increases, probability increases because almost every walk eventually comes back.

2. For d=2, also increases to 1.
3. For d=3, it increases a little and then stabilize below 1 because many walks never return.

## Explanation for part (f)
As the path length increases, the proportion of paths returning to the origin increases in all dimensions. For d=1 and d=2, the return proportion approaches 1, indicating recurrent behaviour. For d=3, the return proportion remains significantly below 1 even for very long paths, indicating transient behaviour. Higher dimensions provide more directions for the walk to escape, making returns to the origin less likely.

## Explanation for part (g)
The key idea: Simulation is finite

We only observe:

* finite number of paths
* finite number of steps

But recurrence is about ∞ time.
A walk may fail to return during 10000 steps but return at step 10^8
which simulation never sees. Similarly seeing many returns in simulation does not prove infinitely many returns.
"""