# -*- coding: utf-8 -*-
"""SMF_Assignment1_q4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWB6LjH2V7RfkxnNDffTXykoqtal--h2

# Question 4 Simulation part

## Part (b)
"""

import numpy as np

P = np.array([
    [0.60,0.30,0.10,0.00],
    [0.20,0.50,0.20,0.10],
    [0.10,0.30,0.40,0.20],
    [0.05,0.15,0.30,0.50]
])

eigvals,eigvecs=np.linalg.eig(P.T) # It finds all eigenvalues and eigenvectors of P^T.
# normally python's eigen vector equation solves for column vector,but here pie is a row vector so we take transpose of the matrix.

idx=np.argmin(np.abs(eigvals-1))
# For every Markov chain there is always an eigenvalue 1, so finds the eigenvalue closest to 1.

pi=np.real(eigvecs[:,idx]) # extracts the corresponding eigenvector.Sum is not 1. so we divide this whole by the total sum.

pi=pi/pi.sum()

print(pi)

"""we start from πP=π.
Move everything to one side and factor out π :- π(P−I)=0.
-> This is exactly an eigenvector problem.

# Part (c)
## Interpretation of πi

Stationary probabilities represents Long-run fraction of weeks spent in each regime.
So,
Over a very long period:
* about 25% weeks are Bull
* about 35% weeks are Neutral
* about 25% weeks are Bear
* about 16% weeks are Crisis
	​

## Part (f)
"""

import numpy as np

P = np.array([
    [0.60,0.30,0.10,0.00],
    [0.20,0.50,0.20,0.10],
    [0.10,0.30,0.40,0.20],
    [0.05,0.15,0.30,0.50]
])

n_steps = 10000

state = 0

path = [state]

for _ in range(n_steps):

    state = np.random.choice(
        [0,1,2,3],
        p=P[state]
    )

    path.append(state)

"""## Part (g)"""

path = np.array(path)

for s in range(4):

    print(
        s,
        np.mean(path==s)
    )

"""## Part (h)"""

returns = np.array([
    0.012,
    0.004,
   -0.006,
   -0.025
])

empirical_return = np.mean(
    returns[path]
)

print(empirical_return)

"""The result is nearly same as calculated theoretical value.

## Part (i)
"""

import matplotlib.pyplot as plt

cum_return = np.cumsum(
    returns[path]
)

plt.plot(cum_return)

plt.xlabel("Week")
plt.ylabel("Cumulative Return")

plt.title("Portfolio Performance")

plt.show()

"""## Part (j)

The stationary distribution describes only long-run average behaviour. Simulation provides information about finite-horizon behaviour, sample-path variability, regime durations, drawdowns, and realized portfolio performance. It also serves as a numerical verification of theoretical results and remains useful when analytical solutions become difficult or impossible to obtain.
"""