# -*- coding: utf-8 -*-
"""SMF_Assignment_1_q.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gfSk9jQB1onJn-mMdrXc4KfBXiAf3MiU

# Question 2 Simulation part
Simulate one path of length 100 starting from state 0
"""

import numpy as np

P = np.array([
    [0.60, 0.25, 0.05, 0.10],
    [0.00, 0.50, 0.50, 0.00],
    [0.00, 0.50, 0.50, 0.00],
    [0.00, 0.00, 0.00, 1.00]
])

n_steps = 100

path = [0]          # start from state 0
current = 0

for _ in range(n_steps):
    current = np.random.choice(
        [0,1,2,3],
        p=P[current]
    )
    path.append(current)

print(path)

"""Simulate 1000 paths and estimate proportions"""

import numpy as np

P = np.array([
    [0.60, 0.25, 0.05, 0.10],
    [0.00, 0.50, 0.50, 0.00],
    [0.00, 0.50, 0.50, 0.00],
    [0.00, 0.00, 0.00, 1.00]
])

n_paths = 1000
n_steps = 100

final_states = []

for _ in range(n_paths):

    state = 0

    for _ in range(n_steps):
        state = np.random.choice(
            [0,1,2,3],
            p=P[state]
        )

    final_states.append(state)

final_states = np.array(final_states)

prop_state3 = np.mean(final_states == 3)

prop_class12 = np.mean(
    (final_states == 1) |
    (final_states == 2)
)

print("Proportion in state 3 =", prop_state3)
print("Proportion in class {1,2} =", prop_class12)

"""Explanation of the result:-
<br>
Starting from state 0:
* eventually leave state 0
* once enter {1,2}, never leave
* if enter state 3, stay forever

So after a very long time: all probability mass ends up in either {1,2} or {3} and none remains in state 0.

Theoretical answers:<br>
From state 0:
* stay in 0 with probability 0.6
* leave 0 with probability 0.4

Conditional on leaving:

P(1)= 0.25/0.40 =0.625
<br>
P(2)= 0.05/0.40 =0.125
<br>
P(3)=0.10/0.40 =0.25

Thus:

P(eventually hit 3)=0.25

P(eventually enter {1,2})=0.75
Therefore after 100 steps we see values around 0.25 and 0.75.

## Interpretation in credit-risk language

Closed class {3}:- State 3 is Default.
Once a firm defaults, it remains defaulted forever in this model.

Therefore {3} represents permanent default.

Closed class {1,2}:-

States:
* 1 = Speculative Grade
* 2 = Distressed

Once the bond enters this class, it keeps fluctuating between these two weak credit-quality states and never returns to Investment Grade or reaches Default in this model.

Thus {1,2} represents a firm trapped in a persistent high-risk credit condition.
"""