# -*- coding: utf-8 -*-
"""Assignment_2_q1_SMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKfK1Ry7RgmK50ypXHIfnGgdp1VvBNe4

# Question 1: Empirical Central Limit Theorem

## Simulation part
"""

import numpy as np
N=10000
n = 10
samples = np.random.binomial(1,0.5,size=(N,n))
S = samples.sum(axis=1)
print(S[:10])

Z=(S-n*0.5)/np.sqrt(n*0.25)

import matplotlib.pyplot as plt
plt.hist(Z,bins=15,density=True)
plt.show()

from scipy . stats import norm
x = np . linspace ( -4 , 4 , 1000)
plt.hist (Z ,bins =15 ,density = True)
plt.plot(x,norm.pdf(x))
plt . show ()

import numpy as np
N=10000
n = 50
samples = np.random.binomial(1,0.5,size=(N,n))
S = samples.sum(axis=1)
print(S[:10])

Z1=(S-n*0.5)/np.sqrt(n*0.25)

import matplotlib.pyplot as plt
plt.hist(Z,bins=15,density=True)
plt.show()

from scipy.stats import norm
x = np . linspace ( -4 , 4 , 1000)
plt.hist (Z1 ,bins =15 ,density = True)
plt.plot(x,norm.pdf(x))
plt . show ()

import numpy as np
N=10000
n = 200
samples = np.random.binomial(1,0.5,size=(N,n))
S = samples.sum(axis=1)
print(S[:10])

Z2=(S-n*0.5)/np.sqrt(n*0.25)

import matplotlib.pyplot as plt
plt.hist(Z,bins=15,density=True)
plt.show()

from scipy . stats import norm
x = np . linspace ( -4 , 4 , 1000)
plt.hist (Z1 ,bins =15 ,density = True)
plt.plot(x,norm.pdf(x))
plt . show ()

"""## part (c)"""

import numpy as np

N = 10000

n_values = [10, 50, 200]

results = {}

for n in n_values:

    samples = np.random.binomial(
        1,
        0.5,
        size=(N, n)
    )

    S = samples.sum(axis=1)

    Z = (S - n/2) / np.sqrt(n/4)

    results[n] = Z

"""## part (d)"""

import matplotlib.pyplot as plt

for n in n_values:

    plt.figure(figsize=(6,4))

    plt.hist(
        results[n],
        bins=40,
        density=True
    )

    plt.title(f"n = {n}")

    plt.show()

"""## Part (e)"""

from scipy.stats import norm

x = np.linspace(-4,4,1000)

for n in n_values:

    plt.figure(figsize=(6,4))

    plt.hist(
        results[n],
        bins=40,
        density=True,
        alpha=0.7
    )

    plt.plot(
        x,
        norm.pdf(x),
        linewidth=2
    )

    plt.title(f"n = {n}")

    plt.show()

"""## Part (f)

1. n = 10

* Histogram still looks somewhat discrete and jagged.

2. n = 50
* Much smoother and starts resembling bell curve

3. n = 200
* Very close to gaussian and bell shape becomes clear.

So,as n increases, the standardized sum becomes increasingly bell-shaped and approaches the standard normal distributio

## part (g)
"""

for n in n_values:

    mean = np.mean(results[n])

    var = np.var(results[n])

    print(
        f"n={n}: mean={mean:.4f}, variance={var:.4f}"
    )

"""Note:- All the means are around 0 and all the variances around 1.

## Part (h)

The simulation demonstrates the Central Limit Theorem by showing that the standardized sums of independent Bernoulli random variables become increasingly close to a standard normal distribution as n increases. The histograms become more bell-shaped and align more closely with the standard Gaussian density, while the empirical means and variances remain close to 0 and 1 respectively.
"""