# -*- coding: utf-8 -*-
"""Assignment_2_q2_SMF.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_HKqiEXsspQEOsrZMz3fzG8tGqqPnd-

# Question 2: Monte Carlo Integration

## Simulation part

## Part (b)
"""

import numpy as np

N_values = [100,1000,10000,100000]

for N in N_values:

    U = np.random.uniform(
        0,
        1,
        size=N
    )

    estimate = np.mean(
        np.exp(-U**2)
    )

    print(
        f"N={N}, estimate={estimate}"
    )

"""## Part (c)"""

from scipy.integrate import quad
import numpy as np

true_value, _ = quad(
    lambda x: np.exp(-x**2),
    0,
    1
)

print(true_value)

from scipy.integrate import quad
import numpy as np

true_value, _ = quad(
    lambda x: np.exp(-x**2),
    0,
    1
)

N_values = [100,1000,10000,100000]

for N in N_values:

    U = np.random.uniform(
        0,
        1,
        size=N
    )

    estimate = np.mean(
        np.exp(-U**2)
    )

    error = abs(
        estimate - true_value
    )

    print(
        f"N={N}"
    )

    print(
        f"Estimate={estimate:.6f}"
    )

    print(
        f"Error={error:.6f}"
    )

    print()

"""## Part (d)"""

import matplotlib.pyplot as plt
import numpy as np
from scipy.integrate import quad

true_value,_ = quad(
    lambda x: np.exp(-x**2),
    0,
    1
)

N_values = [100,1000,10000,100000]

estimates = []

for N in N_values:

    U = np.random.uniform(
        0,
        1,
        size=N
    )

    estimate = np.mean(
        np.exp(-U**2)
    )

    estimates.append(
        estimate
    )

plt.plot(
    N_values,
    estimates,
    marker='o'
)

plt.axhline(
    true_value,
    linestyle='--'
)

plt.xscale('log')

plt.xlabel('N')

plt.ylabel('Estimate')

plt.title('Monte Carlo Estimate')

plt.show()

"""As N increases, the sample average becomes more stable and converges to the true expectation by the Law of Large Numbers. The Monte Carlo error decreases approximately at the rate 1/sqrt(N)."""