# -*- coding: utf-8 -*-
"""Assignment_2_q4_SMF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12ktTfSUCgGOXrZCGFg744Ft7ozimKn0Q

# Question 4: Monte Carlo Option pricing

## Simulation part

## Part (b)
"""

import numpy as np

N = 100000

S0 = 100
sigma = 0.2

Z = np.random.normal(
    0,
    1,
    size=N
)

ST = S0 * np.exp(
    sigma * Z
)

"""## Part (c)"""

payoff = np.maximum(
    ST - 110,
    0
)

"""## Part (d)

"""

option_price = np.mean(
    payoff
)

print(option_price)

"""Interpretation: Average payoff over all simulated futures.

This is the Monte Carlo estimate of E[(ST−K)^+].

## Part (e)
"""

import matplotlib.pyplot as plt

plt.hist(
    ST,
    bins=50,
    density=True
)

plt.title(
    "Terminal Stock Prices"
)

plt.show()

"""## Part (f)"""

plt.hist(
    payoff,
    bins=50,
    density=True
)

plt.title(
    "Call Option Payoffs"
)

plt.show()

"""Large spike at 0 because many simulations finish below the strike. Then a long right tail.

## Part (g)
"""

vols = [0.1,0.3,0.5]

for sigma in vols:

    Z = np.random.normal(
        0,
        1,
        size=N
    )

    ST = S0*np.exp(
        sigma*Z
    )

    payoff = np.maximum(
        ST-110,
        0
    )

    estimate = np.mean(
        payoff
    )

    print(
        sigma,
        estimate
    )

"""## Part (h)

Increasing volatility increases the dispersion of terminal stock prices. Since a call option has limited downside and unlimited upside, higher volatility generally increases the expected option payoff and therefore increases the option value.

## Part (i)

Monte Carlo methods are useful in derivative pricing because they can estimate expected payoffs by simulating many possible future market scenarios. They are particularly valuable for complex derivatives where closed-form pricing formulas do not exist.
"""