# -*- coding: utf-8 -*-
"""Assignment_2_q3_SMFipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VTBp8w44mv-TRTlyR3zD1MamfPyGeXV

# Question 3: Monte carlo estimation of π

## Simulation part

## Part (b)
"""

import numpy as np

N_values = [100, 1000, 10000, 100000]

for N in N_values:

    x = np.random.uniform(-1, 1, size=N)
    y = np.random.uniform(-1, 1, size=N)

    inside = (x**2 + y**2) <= 1

    pi_estimate = 4 * np.mean(inside)

    print(
        f"N={N}, pi estimate={pi_estimate}"
    )

inside = (x**2 + y**2) <= 1
np.mean(inside)

"""## Part (d)"""

import numpy as np
import matplotlib.pyplot as plt

N = 5000

x = np.random.uniform(-1,1,size=N)
y = np.random.uniform(-1,1,size=N)

inside = (x**2 + y**2) <= 1

plt.figure(figsize=(6,6))

plt.scatter(
    x[inside],
    y[inside],
    s=5,
    label="Inside Circle"
)

plt.scatter(
    x[~inside],
    y[~inside],
    s=5,
    label="Outside Circle"
)

plt.legend()

plt.axis('equal')

plt.title("Monte Carlo Estimation of π")

plt.show()

"""## Part (e)"""

import numpy as np
import matplotlib.pyplot as plt

N_values = [100,1000,10000,100000]

estimates = []

for N in N_values:

    x = np.random.uniform(-1,1,size=N)
    y = np.random.uniform(-1,1,size=N)

    inside = (x**2 + y**2) <= 1

    pi_estimate = 4*np.mean(inside)

    estimates.append(pi_estimate)

plt.plot(
    N_values,
    estimates,
    marker='o'
)

plt.axhline(
    np.pi,
    linestyle='--',
    label='True π'
)

plt.xscale('log')

plt.xlabel('N')
plt.ylabel('π estimate')

plt.legend()

plt.show()

"""## Part (f)

As the number of sampled points increases, the sample proportion inside the circle converges to the true probability π/4. Hence the estimator converges to the true value of π.
"""

import numpy as np

N_values = [100,1000,10000,100000]

for N in N_values:

    x = np.random.uniform(-1,1,size=N)
    y = np.random.uniform(-1,1,size=N)

    inside = (x**2 + y**2) <= 1

    estimate = 4*np.mean(inside)

    error = abs(
        estimate - np.pi
    )

    print(
        f"N={N}"
    )

    print(
        f"Estimate={estimate:.6f}"
    )

    print(
        f"Error={error:.6f}"
    )

    print()

"""## Part (g)
The Monte Carlo estimate approaches the true value π≈3.14159 as N increases. The absolute error generally decreases with larger sample sizes, demonstrating convergence predicted by the Law of Large Numbers.
"""